version: '3.7'

services:
  spark:
    build:
      dockerfile: ./dockerfiles/spark/dockerfile
    container_name: spark
    volumes:
      - ./includes:/includes
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001

#   # source: https://github.com/developer-advocacy-dremio/iceberg-intro-lessons/blob/main/docker-compose.yml
  nessie:
    image: projectnessie/nessie:0.67.0
    container_name: nessie
    ports:
      - 19120:19120

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    container_name: minio
    env_file:
      - secrets.env
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  dremio:
    platform: linux/x86_64
    container_name: dremio
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010

# Kafka compose source: https://medium.com/@erkndmrl/kafka-cluster-with-docker-compose-5864d50f677e
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1